name: Bot
permissions: 
  pull-requests: write
  contents: write
  statuses: write
on:
  pull_request:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAIN_BRANCH_NAME: 'main'
        BASE_PR_REF: ${{ github.base_ref }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: List Envs
        run: env
        
      - name: Script
        run: ./script.sh